# Generated by Django 5.1.4 on 2025-06-22 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_url', models.ImageField(default='images/playlist_thumbnail/default_image.png', upload_to='images/playlist_thumbnail')),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Collaborator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('song', 'playlist')},
            },
        ),
    ]
