version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - ./backend/.env
    # environment:
    #   POSTGRES_USER: arnabdas
    #   POSTGRES_PASSWORD: arnab@123
    #   POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-1
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - static-files:/app/static
      - media-files:/app/media
    ports:
      - 8000:8000
    depends_on:
      - db

  backend-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-2
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - static-files:/app/static
      - media-files:/app/media
    # ports:
    #   - 8001:8000
    depends_on:
      - db

  backend-3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-3
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - static-files:/app/static
      - media-files:/app/media
    # ports:
    #   - 8002:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    # ports:
    #   - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static-files:/app/static
      - media-files:/app/media
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend-1
      - backend-2
      - backend-3
      - frontend

volumes:
  postgres_data:
  media-files:
  static-files:
