# Generated by Django 5.1.4 on 2025-06-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song_Features',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song', unique=True)),
            ],
        ),
    ]
