# Generated by Django 5.1.4 on 2025-07-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.ImageField(default='images/radio_thumbnail/default_image.png', upload_to='images/radio_thumbnail')),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radio_Queue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.radio')),
            ],
        ),
        migrations.CreateModel(
            name='Radio_Seed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.radio')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song')),
            ],
        ),
    ]
