# Generated by Django 5.1.4 on 2025-06-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.ImageField(default='images/album_thumbnail/default_image.png', upload_to='images/album_thumbnail')),
                ('release_date', models.DateField()),
                ('release_type', models.CharField(choices=[('Single', 'Single'), ('Album', 'Album'), ('EP', 'EP')], max_length=10)),
                ('duration', models.DurationField()),
                ('is_explicit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('profile_image_url', models.ImageField(default='images/artist_profile_image/default_image.png', upload_to='images/artist_profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cover_image_url', models.ImageField(default='images/genre_cover_image/default_image.png', upload_to='images/genre_cover_image')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.FileField(default='tracks/default.mp3', upload_to='tracks')),
                ('thumbnail_url', models.ImageField(default='images/song_thumbnail/default_image.png', upload_to='images/song_thumbnail')),
                ('lyrics_url', models.FileField(blank=True, upload_to='lyrics')),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('is_explicit', models.BooleanField(default=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.version')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.artist')),
            ],
            options={
                'unique_together': {('album', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='Artist_Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.genre')),
            ],
            options={
                'unique_together': {('artist', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Genre_Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.genre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song')),
            ],
            options={
                'unique_together': {('genre', 'song')},
            },
        ),
        migrations.CreateModel(
            name='Artist_Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='Singer', max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song')),
            ],
            options={
                'unique_together': {('artist', 'song')},
            },
        ),
        migrations.CreateModel(
            name='Album_Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('album', 'song')},
            },
        ),
        migrations.CreateModel(
            name='Song_Version',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('refer_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refer_song', to='content.song')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='content.song')),
            ],
            options={
                'unique_together': {('song', 'refer_song')},
            },
        ),
    ]
